import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/Shared/UI/Header/Header";
import "bootswatch/dist/litera/bootstrap.min.css";
import "./globals.css";
import "@state/store";
import ReduxProvider from "@/Shared/UI/ReduxProvider/ReduxProvider";
import AlertContainer from "@/Features/SelfClosingAlert/AlertContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <div className="d-flex flex-column vh-100 position-relative">
          <ReduxProvider>
            <Header />
            <AlertContainer />
            <div className="h-100">{children}</div>
          </ReduxProvider>
        </div>
      </body>
    </html>
  );
}
